---
theme: "dealing-with-bots-theme"
languageCode: "en-gb"
uglyURLs: false
title: "Dealing With Bots: A COAR Resource for Repository Managers"
enableRobotsTXT: true
enableGitInfo: false
disablePathToLower: true
services:
  rss:
    limit: 20
#outputFormats:
#  markdown:
#    mediaType: "text/markdown"
#    baseName: "index"
#    isPlainText: true
outputs:
  home:
    - html
  section:
    - html
    - rss
  taxonomy:
    - html
  term:
    - html
  page:
    - html
menus:
  main:
    - name: Background
      weight: 11
taxonomies:
  tag: "tags"
caches:
  getjson:
    dir: :cacheDir/:project
    maxAge: 5s
  getresource:
    dir: :cacheDir/:project
    maxAge: 5s
  getcsv:
    dir: :cacheDir/:project
    maxAge: 5s
params:
  citation_authors: "Paul Walk; The Dealing With Bots COAR Task Group"
  gitHubRepoForSources: "https://github.com/coar-repositories/dealing-with-bots"
  headerMessages:
#    - type: danger
#      message: "This website is in active development and is **not yet ready to be used as a reference**. Please check back later."
markup:
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: false
      strikethrough: true
      table: true
      taskList: true
      typographer: false
      extras:
        delete:
          enable: true
        insert:
          enable: true
        mark:
          enable: true
        subscript:
          enable: false
        superscript:
          enable: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    lineAnchors: ""
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    style: pygments
    tabWidth: 4
---